### ISSUE TITLE
My first project

### ISSUE THREAD

**Issue by Subra730** [cganesh8/New-idea#1]
I am thinking of a new project, will outline in the WiKi

**Comment by cganesh8** [comment]
That's fantastic! 👍  This could truly be the light at the end of the tunnel **or** an oncoming train! .

While you're putting you're putting your brainwaves to electronic paper (Wiki), you may want to take a look at the following youtube videos on GitHub - **Introduction - GiT & Github**

[https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV&index=1](url)

They are really good. I am going through them myself.

**Comment by cganesh8** [comment]
Suggested a youtube link on Github
